# Generated by Django 4.1 on 2022-11-25 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_follow"),
    ]

    operations = [
        migrations.RemoveField(model_name="follow", name="followed",),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="followed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
