# Generated by Django 4.1 on 2022-11-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_alter_follow_followed_alter_follow_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow", old_name="user", new_name="following",
        ),
    ]
